on:
  push:
    branches:
        -main
        
   jobs:
      builds:
         runs-on:
          steps:
              -name: Checkout
               uses: actions/checkout@v3.3.0
               -run: docker build-t Shaastra-api
              
               
